"""Type stub for mixin classes.

This stub file declares:
1. The methods defined by each mixin class
2. The attributes from PorePyModel that the mixin expects via duck typing

This allows type checkers to understand the mixin interface without
requiring runtime inheritance from PorePyModel.
"""

from typing import Any

class FluidDensityFromPressure:
    # Attributes expected from PorePyModel (via duck typing)
    equation_system: Any
    fluid: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any

    def fluid_compressibility(self, subdomains: ...) -> None: ...
    def density_of_phase(self, phase: ...) -> None: ...
    def pressure_exponential(self, subdomains: ...) -> None: ...

class FluidDensityFromTemperature:
    # Attributes expected from PorePyModel (via duck typing)
    equation_system: Any
    fluid: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any

    def fluid_thermal_expansion(self, subdomains: ...) -> None: ...
    def density_of_phase(self, phase: ...) -> None: ...
    def temperature_exponential(self, subdomains: ...) -> None: ...

class FluidMobility:
    # Attributes expected from PorePyModel (via duck typing)
    equation_system: Any
    fluid: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any

    def mobility_discretization(self, subdomains: ...) -> None: ...
    def interface_mobility_discretization(self, interfaces: ...) -> None: ...
    def total_mass_mobility(self, domains: ...) -> None: ...
    def phase_mobility(self, phase: ..., domains: ...) -> None: ...
    def component_mass_mobility(self, component: ..., domains: ...) -> None: ...
    def fractional_component_mass_mobility(self, component: ..., domains: ...) -> None: ...
    def fractional_phase_mass_mobility(self, phase: ..., domains: ...) -> None: ...

class FluidBuoyancy:
    # Attributes expected from PorePyModel (via duck typing)
    equation_system: Any
    fluid: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any

    def buoyancy_key(self, gamma: ..., delta: ...) -> None: ...
    def buoyant_flux_array_key(self, gamma: ..., delta: ...) -> None: ...
    def buoyancy_intf_key(self, gamma: ..., delta: ...) -> None: ...
    def buoyant_intf_flux_array_key(self, gamma: ..., delta: ...) -> None: ...
    def buoyancy_discretization(self, gamma: ..., delta: ..., subdomains: ...) -> None: ...
    def interface_buoyancy_discretization(self, gamma: ..., delta: ..., interfaces: ...) -> None: ...
    def fractionally_weighted_density(self, domains: ...) -> None: ...
    def gravity_field(self, subdomains: ...) -> None: ...
    def gravity_force(self, subdomains: ..., material: ...) -> None: ...
    def density_driven_flux(self, subdomains: ..., density_metric: ...) -> None: ...
    def interface_density_driven_flux(self, interfaces: ..., density_metric: ...) -> None: ...
    def __entity_buoyancy_flux(self, advected_gamma_quantity: ..., gamma: ..., delta: ..., domains: ...) -> None: ...
    def __entity_buoyancy_jump(self, advected_gamma_quantity: ..., gamma: ..., delta: ..., domains: ...) -> None: ...
    def phase_pairs_for(self, phase: ...) -> None: ...
    def component_buoyancy(self, component_xi: ..., domains: ...) -> None: ...
    def enthalpy_buoyancy(self, domains: ...) -> None: ...
    def component_buoyancy_jump(self, component_xi: ..., domains: ...) -> None: ...
    def enthalpy_buoyancy_jump(self, domains: ...) -> None: ...
    def set_buoyancy_discretization_parameters(self) -> None: ...
    def set_nonlinear_buoyancy_discretization(self) -> None: ...
    def update_buoyancy_driven_fluxes(self) -> None: ...

class ConstantViscosity:
    # Attributes expected from PorePyModel (via duck typing)
    equation_system: Any
    fluid: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any

    def viscosity_of_phase(self, phase: ...) -> None: ...

class ConstantFluidThermalConductivity:
    # Attributes expected from PorePyModel (via duck typing)
    equation_system: Any
    fluid: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any

    def thermal_conductivity_of_phase(self, phase: ...) -> None: ...
    def normal_thermal_conductivity(self, interfaces: ...) -> None: ...

class FluidEnthalpyFromTemperature:
    # Attributes expected from PorePyModel (via duck typing)
    equation_system: Any
    fluid: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any

    def fluid_specific_heat_capacity(self, subdomains: ...) -> None: ...
    def specific_enthalpy_of_phase(self, phase: ...) -> None: ...
