"""Type stub for mixin classes.

This stub file declares:
1. The methods defined by each mixin class
2. The attributes from PorePyModel that the mixin expects via duck typing

This allows type checkers to understand the mixin interface without
requiring runtime inheritance from PorePyModel.
"""

from typing import Any

class ModelGeometry:
    # Attributes expected from PorePyModel (via duck typing)
    domain: Any
    fracture_network: Any
    fractures: Any
    mdg: Any
    nd: Any
    params: Any
    units: Any
    well_network: Any

    def set_geometry(self) -> None: ...
    def domain(self) -> None: ...
    def set_domain(self) -> None: ...
    def fractures(self) -> None: ...
    def set_fractures(self) -> None: ...
    def create_fracture_network(self) -> None: ...
    def create_mdg(self) -> None: ...
    def set_well_network(self) -> None: ...
    def is_well(self, grid: ...) -> None: ...
    def grid_type(self) -> None: ...
    def meshing_arguments(self) -> None: ...
    def meshing_kwargs(self) -> None: ...
    def subdomains_to_interfaces(self, subdomains: ..., codims: ...) -> None: ...
    def interfaces_to_subdomains(self, interfaces: ...) -> None: ...
    def subdomains_to_boundary_grids(self, subdomains: ...) -> None: ...
    def wrap_grid_attribute(self, grids: ..., attr: ...) -> None: ...
    def basis(self, grids: ..., dim: ...) -> None: ...
    def e_i(self, grids: ...) -> None: ...
    def tangential_component(self, subdomains: ...) -> None: ...
    def normal_component(self, subdomains: ...) -> None: ...
    def local_coordinates(self, subdomains: ...) -> None: ...
    def subdomain_projections(self, dim: ...) -> None: ...
    def domain_boundary_sides(self, domain: ..., tol: ...) -> None: ...
    def internal_boundary_normal_to_outwards(self, subdomains: ...) -> None: ...
    def outwards_internal_boundary_normals(self, interfaces: ...) -> None: ...
