"""Type stub for mixin classes.

This stub file declares:
1. The methods defined by each mixin class
2. The attributes from PorePyModel that the mixin expects via duck typing

This allows type checkers to understand the mixin interface without
requiring runtime inheritance from PorePyModel.
"""

from typing import Any

class SolutionStrategy:
    # Attributes expected from PorePyModel (via duck typing)
    ad_time_step: Any
    convergence_status: Any
    equation_system: Any
    linear_system: Any
    mdg: Any
    nd: Any
    nonlinear_solver_statistics: Any
    numerical: Any
    params: Any
    reference_variable_values: Any
    restart_options: Any
    results: Any
    solid: Any
    time_manager: Any
    units: Any

    def __init__(self, params: ...) -> None: ...
    def prepare_simulation(self) -> None: ...
    def initialize_previous_iterate_and_time_step_values(self) -> None: ...
    def set_equation_system_manager(self) -> None: ...
    def set_solver_statistics(self) -> None: ...
    def time_step_indices(self) -> None: ...
    def iterate_indices(self) -> None: ...
    def schur_complement_primary_equations(self) -> None: ...
    def schur_complement_primary_equations(self, names: ...) -> None: ...
    def schur_complement_primary_variables(self) -> None: ...
    def schur_complement_primary_variables(self, names: ...) -> None: ...
    def reset_state_from_file(self) -> None: ...
    def set_materials(self) -> None: ...
    def discretize(self) -> None: ...
    def nonlinear_discretizations(self) -> None: ...
    def nonlinear_diffusive_flux_discretizations(self) -> None: ...
    def add_nonlinear_discretization(self, discretization: ...) -> None: ...
    def add_nonlinear_diffusive_flux_discretization(self, discretization: ...) -> None: ...
    def set_nonlinear_discretizations(self) -> None: ...
    def before_nonlinear_loop(self) -> None: ...
    def before_nonlinear_iteration(self) -> None: ...
    def after_nonlinear_iteration(self, nonlinear_increment: ...) -> None: ...
    def after_nonlinear_convergence(self) -> None: ...
    def update_solution(self, solution: ...) -> None: ...
    def after_nonlinear_failure(self) -> None: ...
    def after_simulation(self) -> None: ...
    def check_convergence(self, nonlinear_increment: ..., residual: ..., reference_residual: ..., nl_params: ...) -> None: ...
    def compute_residual_norm(self, residual: ..., reference_residual: ...) -> None: ...
    def compute_nonlinear_increment_norm(self, nonlinear_increment: ...) -> None: ...
    def _initialize_linear_solver(self) -> None: ...
    def assemble_linear_system(self) -> None: ...
    def solve_linear_system(self) -> None: ...
    def _apply_schur_complement_reduction(self) -> None: ...
    def _is_nonlinear_problem(self) -> None: ...
    def _is_time_dependent(self) -> None: ...
    def _is_reference_phase_eliminated(self) -> None: ...
    def _is_reference_component_eliminated(self) -> None: ...
    def update_time_dependent_ad_arrays(self) -> None: ...
    def update_derived_quantities(self) -> None: ...
    def update_material_properties(self) -> None: ...
    def update_discretization_parameters(self) -> None: ...
    def rediscretize_fluxes(self) -> None: ...
    def update_flux_values(self) -> None: ...
    def rediscretize(self) -> None: ...
    def darcy_flux_storage_keywords(self) -> None: ...

class ContactIndicators:
    # Attributes expected from PorePyModel (via duck typing)
    ad_time_step: Any
    convergence_status: Any
    equation_system: Any
    linear_system: Any
    mdg: Any
    nd: Any
    nonlinear_solver_statistics: Any
    numerical: Any
    params: Any
    reference_variable_values: Any
    restart_options: Any
    results: Any
    solid: Any
    time_manager: Any
    units: Any

    def opening_indicator(self, subdomains: ...) -> None: ...
    def sliding_indicator(self, subdomains: ...) -> None: ...
    def contact_traction_estimate(self, subdomains: ...) -> None: ...
    def compute_traction_norm(self, val: ...) -> None: ...
