# Purpose: Rebase the docs branch on top of develop. This will ensure that docs is
# always downstream from develop.
# Acknowledgements: https://github.com/marketplace/actions/local-git-rebase

name: Rebase docs on develop
on:
  push:
    branches:
      # All pushes to this branch will trigger the task.
      - develop

jobs:
  rebase_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase docs on develop
        # Recommended: specify a version such as `@v1.0` rather than `@main`
        uses: DeeDeeG/rebase-github-action@main
        with:
          # Head branch, which will be rebased onto the base_ref.
          head_branch: docs
          # Branch, or Git ref, that the head_branch will be rebased onto.
          base_ref: develop
